=== MrJohnAdib/resume/schema/experience-profile.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"title": {
			"type": "string",
			"minLength": 1
		},
		"organization": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"url": {
					"type": "string"
				},
				"linkEnabled": {
					"type": "boolean"
				}
			},
			"required": [
				"name",
				"url"
			],
			"additionalProperties": {}
		},
		"employmentType": {
			"type": "string"
		},
		"location": {
			"type": "string"
		},
		"duration": {
			"type": "string"
		},
		"dynamicDuration": {
			"type": "boolean"
		},
		"dates": {
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				},
				"end": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"start",
				"end"
			],
			"additionalProperties": false
		}
	},
	"required": [
		"title",
		"organization",
		"employmentType",
		"location",
		"duration",
		"dynamicDuration",
		"dates"
	],
	"additionalProperties": false
}

=== MrJohnAdib/resume/data/sections/experience/co-founder-cto/profile.json
{
	"title": "Co-Founder & CTO",
	"organization": {
		"name": "Jibres",
		"url": "https://jibres.com",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "IR",
	"duration": "(3 years)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2019-12-06",
			"label": "12/2019"
		},
		"end": {
			"datetime": "2022-11",
			"label": "11/2022"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/head-of-engineering/profile.json
{
	"title": "Head of Engineering",
	"organization": {
		"name": "Ermile",
		"url": "https://ermile.com/",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "IR",
	"duration": "(1 year 5 months)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2018-08-07",
			"label": "08/2018"
		},
		"end": {
			"datetime": "2019-12-06",
			"label": "12/2019"
		}
	}
}
