=== MrJohnAdib/resume/schema/experience-profile.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"title": {
			"type": "string",
			"minLength": 1
		},
		"organization": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"url": {
					"type": "string"
				},
				"linkEnabled": {
					"type": "boolean"
				}
			},
			"required": [
				"name",
				"url"
			],
			"additionalProperties": {}
		},
		"employmentType": {
			"type": "string"
		},
		"location": {
			"type": "string"
		},
		"duration": {
			"type": "string"
		},
		"dynamicDuration": {
			"type": "boolean"
		},
		"dates": {
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				},
				"end": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"start",
				"end"
			],
			"additionalProperties": false
		}
	},
	"required": [
		"title",
		"organization",
		"employmentType",
		"location",
		"duration",
		"dynamicDuration",
		"dates"
	],
	"additionalProperties": false
}

=== MrJohnAdib/resume/data/sections/experience/engineering-manager-promoted-from-senior/profile.json
{
	"title": "Engineering Manager (Promoted from Senior)",
	"organization": {
		"name": "Zapp",
		"url": "https://justzapp.com",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "London",
	"duration": "(1 year 8 months)",
	"dynamicDuration": true,
	"dates": {
		"start": {
			"datetime": "2024-12-16",
			"label": "12/2024"
		},
		"end": {
			"datetime": "present",
			"label": "Present"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/computer-lecturer/profile.json
{
	"title": "Computer Lecturer",
	"organization": {
		"name": "Teacher",
		"url": "",
		"linkEnabled": false
	},
	"employmentType": "Part-time",
	"location": "IR",
	"duration": "(11 years 4 months)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2006-06",
			"label": "06/2006"
		},
		"end": {
			"datetime": "2017-09",
			"label": "09/2017"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/principal-software-engineer/profile.json
{
	"title": "Principal Software Engineer",
	"organization": {
		"name": "Tejarak",
		"url": "https://tejarak.com/",
		"linkEnabled": false
	},
	"employmentType": "Full-time",
	"location": "IR",
	"duration": "(1 year)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2017-09-07",
			"label": "09/2017"
		},
		"end": {
			"datetime": "2018-08-06",
			"label": "08/2018"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/senior-software-engineer/profile.json
{
	"title": "Senior Software Engineer",
	"organization": {
		"name": "Zapp",
		"url": "https://justzapp.com",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "London",
	"duration": "(1 year 5 months)",
	"dynamicDuration": true,
	"dates": {
		"start": {
			"datetime": "2024-12-16",
			"label": "12/2024"
		},
		"end": {
			"datetime": "2026-04-12",
			"label": "04/2026"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/engineering-manager-consumer/profile.json
{
	"title": "Engineering Manager, Consumer",
	"organization": {
		"name": "Zapp",
		"url": "https://justzapp.com",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "London",
	"duration": "(4 months)",
	"dynamicDuration": true,
	"dates": {
		"start": {
			"datetime": "2026-04-13",
			"label": "04/2026"
		},
		"end": {
			"datetime": "present",
			"label": "Present"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/frontend-developer-ui-ux/profile.json
{
	"title": "Frontend Developer UI/UX",
	"organization": {
		"name": "Freelancer",
		"url": "",
		"linkEnabled": false
	},
	"employmentType": "Freelance",
	"location": "IR",
	"duration": "(3 years)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2008-09-22",
			"label": "09/2008"
		},
		"end": {
			"datetime": "2011-08-22",
			"label": "08/2011"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/senior-lead-software-engineer/profile.json
{
	"title": "Senior Lead Software Engineer",
	"organization": {
		"name": "Loopla",
		"url": "https://loopla.com/",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "London",
	"duration": "(2 years 1 month)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2022-12-11",
			"label": "12/2022"
		},
		"end": {
			"datetime": "2024-12-15",
			"label": "12/2024"
		}
	}
}

=== MrJohnAdib/resume/data/sections/experience/co-founder-ceo/profile.json
{
	"title": "Co-Founder & CEO",
	"organization": {
		"name": "Sarshomar",
		"url": "https://sarshomar.com/",
		"linkEnabled": true
	},
	"employmentType": "Full-time",
	"location": "IR",
	"duration": "(2 years 4 months)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2015-06-22",
			"label": "06/2015"
		},
		"end": {
			"datetime": "2019-09-07",
			"label": "09/2017"
		}
	}
}
