=== MrJohnAdib/resume/schema/section-volunteering.schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"minLength": 1,
			"pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
		},
		"status": {
			"type": "string",
			"enum": [
				"current",
				"alternate",
				"archived"
			]
		},
		"title": {
			"type": "string",
			"minLength": 1
		},
		"organization": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1
				},
				"url": {
					"type": "string"
				},
				"linkEnabled": {
					"type": "boolean"
				}
			},
			"required": [
				"name",
				"url"
			],
			"additionalProperties": {}
		},
		"location": {
			"type": "string"
		},
		"duration": {
			"type": "string"
		},
		"dynamicDuration": {
			"type": "boolean"
		},
		"dates": {
			"type": "object",
			"properties": {
				"start": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				},
				"end": {
					"type": "object",
					"properties": {
						"datetime": {
							"type": "string",
							"pattern": "^(?:\\d{4}(?:-(?:0[1-9]|1[0-2])(?:-(?:0[1-9]|[12]\\d|3[01]))?)?|present)$"
						},
						"label": {
							"type": "string"
						}
					},
					"required": [
						"datetime",
						"label"
					],
					"additionalProperties": false
				}
			},
			"required": [
				"start",
				"end"
			],
			"additionalProperties": false
		},
		"bullets": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"id": {
						"type": "string",
						"minLength": 1,
						"pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
					},
					"status": {
						"type": "string",
						"enum": [
							"current",
							"alternate",
							"archived"
						]
					},
					"text": {
						"anyOf": [
							{
								"type": "string"
							},
							{
								"type": "array",
								"items": {
									"oneOf": [
										{
											"type": "object",
											"properties": {
												"type": {
													"type": "string",
													"const": "text"
												},
												"value": {
													"type": "string"
												}
											},
											"required": [
												"type",
												"value"
											],
											"additionalProperties": false
										},
										{
											"type": "object",
											"properties": {
												"type": {
													"type": "string",
													"const": "abbr"
												},
												"value": {
													"type": "string"
												},
												"title": {
													"type": "string"
												}
											},
											"required": [
												"type",
												"value",
												"title"
											],
											"additionalProperties": false
										},
										{
											"type": "object",
											"properties": {
												"type": {
													"type": "string",
													"const": "sup"
												},
												"value": {
													"type": "string"
												}
											},
											"required": [
												"type",
												"value"
											],
											"additionalProperties": false
										}
									]
								}
							}
						]
					},
					"annotations": {
						"type": "array",
						"items": {
							"oneOf": [
								{
									"type": "object",
									"properties": {
										"type": {
											"type": "string",
											"const": "text"
										},
										"value": {
											"type": "string"
										}
									},
									"required": [
										"type",
										"value"
									],
									"additionalProperties": false
								},
								{
									"type": "object",
									"properties": {
										"type": {
											"type": "string",
											"const": "abbr"
										},
										"value": {
											"type": "string"
										},
										"title": {
											"type": "string"
										}
									},
									"required": [
										"type",
										"value",
										"title"
									],
									"additionalProperties": false
								},
								{
									"type": "object",
									"properties": {
										"type": {
											"type": "string",
											"const": "sup"
										},
										"value": {
											"type": "string"
										}
									},
									"required": [
										"type",
										"value"
									],
									"additionalProperties": false
								}
							]
						}
					}
				},
				"required": [
					"id",
					"text"
				],
				"additionalProperties": {}
			}
		}
	},
	"required": [
		"id",
		"title",
		"organization",
		"location",
		"duration",
		"dynamicDuration",
		"dates",
		"bullets"
	],
	"additionalProperties": {}
}

=== MrJohnAdib/resume/data/sections/volunteering/mentor-software-engineering-career-growth.json
{
	"id": "mentor-software-engineering-career-growth",
	"status": "current",
	"title": "Mentor - Software Engineering & Career Growth",
	"organization": {
		"name": "ADPList",
		"url": "https://adplist.org/mentors/john-adib"
	},
	"location": "IR",
	"duration": "(2 years 2 months)",
	"dynamicDuration": true,
	"dates": {
		"start": {
			"datetime": "2024-06",
			"label": "06/2024"
		},
		"end": {
			"datetime": "present",
			"label": "Present"
		}
	},
	"bullets": [
		{
			"id": "mentored-580-sessions-advising-on-roadmaps-best-practices-and-strate",
			"text": "Mentored 580+ sessions, advising on roadmaps, best practices, and strategic decisions in technical and professional domains."
		}
	]
}

=== MrJohnAdib/resume/data/sections/volunteering/cto-volunteer-part-time.json
{
	"id": "cto-volunteer-part-time",
	"status": "current",
	"title": "CTO (Volunteer, Part-time)",
	"organization": {
		"name": "Khadije Charity",
		"url": ""
	},
	"location": "IR",
	"duration": "(4 years 10 months)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2017-12",
			"label": "12/2017"
		},
		"end": {
			"datetime": "2022-09",
			"label": "09/2022"
		}
	},
	"bullets": [
		{
			"id": "founded-and-scaled-the-entire-technical-ecosystem-from-zero-engineered",
			"text": "Founded and scaled the entire technical ecosystem from zero, engineered solutions that directly impacted 110,000+ lives."
		}
	]
}

=== MrJohnAdib/resume/data/sections/volunteering/expert-software-solutions-for-business.json
{
	"id": "expert-software-solutions-for-business",
	"status": "alternate",
	"title": "Expert - Software Solutions for Business",
	"organization": {
		"name": "WorldSkills IR",
		"url": ""
	},
	"location": "IR",
	"duration": "(5 years 3 months)",
	"dynamicDuration": false,
	"dates": {
		"start": {
			"datetime": "2010-06",
			"label": "06/2010"
		},
		"end": {
			"datetime": "2015-08-16",
			"label": "08/2015"
		}
	},
	"bullets": [
		{
			"id": "coached-and-trained-3-national-medalists-managed-second-stage-of-nation",
			"text": "Coached and trained 3 national medalists; Managed second stage of national team camp for WorldSkills Sao Paulo 2015."
		}
	]
}

=== MrJohnAdib/resume/data/sections/volunteering/judge-2025-codie-awards.json
{
	"id": "judge-2025-codie-awards",
	"status": "current",
	"title": "Judge - 2025 CODiE Awards",
	"organization": {
		"name": "CODiE Awards",
		"url": "https://codieawards.com/"
	},
	"location": "IR",
	"duration": "(1 year)",
	"dynamicDuration": true,
	"dates": {
		"start": {
			"datetime": "2025-01",
			"label": "01/2025"
		},
		"end": {
			"datetime": "2025-12",
			"label": "12/2025"
		}
	},
	"bullets": [
		{
			"id": "selected-as-a-2025-judge-to-evaluate-top-global-software-products-recog",
			"text": "Selected as a 2025 judge to evaluate top global software products, recognizing innovation and excellence in technology."
		}
	]
}
